version: "3"

services:
  webserver:
    build:
      context: ./bin/webserver
    container_name: 'png-webserver'
    restart: 'always'
    ports:
      - "11180:80"
      #- "443:443"
    links:
      - mysql
    volumes:
      - /home/odie/test:/var/www/html
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./config/vhosts:/etc/apache2/sites-enabled
      - ./logs/apache2:/var/log/apache2

  mysql:
    build: ./bin/mysql
    container_name: 'png-mysql'
    restart: 'always'
    ports:
      - "13306:3306"
    volumes:
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: tiger
      MYSQL_DATABASE: png
      MYSQL_USER: png
      MYSQL_PASSWORD: png
